spring:
  application:
    name: movierental
  datasource:
    url: jdbc:h2:mem:movie-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging.level.com.etraveli.movierental: DEBUG